# -------------------------------------------
# Projet Variance - Serveur de développement
# -------------------------------------------
services:

  laravel:
    build:
      context: ./laravel
    container_name: laravel
    volumes:
      - ./laravel/app:/var/www/html
    working_dir: /var/www/html
    environment:
      - PHP_MEMORY_LIMIT=512M
    ports:
      - "8000:8000"
    networks:
      - variance

  mariadb:
    image: mariadb:11.5.2
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: variance
      MYSQL_USER: variance_user
      MYSQL_PASSWORD: variance_password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - variance

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    networks:
      - variance

  medite:
    build:
      context: ./medite
    container_name: medite
    volumes:
      - ./medite/app:/app
    working_dir: /app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=flask_app.py
      - NLTK_DATA=/app/assets/nltk_data
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - variance

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - variance

  saxon:
    build:
      context: ./saxon
    container_name: saxon
    volumes:
      - ./saxon/app:/app
    working_dir: /app
    networks:
      - variance

networks:
  variance:
    name: variance

volumes:
  dbdata:
