#!/usr/bin/env python3
"""
txt2tei.py  –  _plain text_ ➔ minimal TEI

• Entire input kept verbatim (new-lines included) inside **one** <p>.
• We collapse runs of spaces/tabs into a single ASCII space, but we leave
  all `\n` characters alone (so line breaks survive).
• xml:id is “v{version_nb}”.

Example
-------
python scripts/txt2tei.py tests/data/LaVendetta/1vndtt.txt \
       --pub_date_str "1842" \
       --titre "La Vendetta" \
       --version_nb 1
"""
from __future__ import annotations
import pathlib, logging, xml.etree.ElementTree as ET
import click
import re

TEI_NS = "http://www.tei-c.org/ns/1.0"
ET.register_namespace("", TEI_NS)
log = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────
def _collapse_spaces_and_tabs(txt: str) -> str:
    """
    Replace every run of spaces or tabs (but NOT newlines) by exactly one ASCII space.
    This leaves \n untouched.
    """
    # First, replace tabs by a space:
    txt = txt.replace("\t", " ")
    # Then collapse any run of two or more spaces into a single space:
    return re.sub(r" {2,}", " ", txt)


def _normalize_characters(txt: str) -> str:
    return (
        txt
        .replace("\u2013", "\u2014")   # en dash → em dash
        .replace("\u2212", "-")       # minus sign → ASCII hyphen‐minus
        .replace("\u2010", "-")       # hyphen → ASCII hyphen‐minus
        .replace("\u2011", "-")       # non‐breaking hyphen → ASCII hyphen‐minus
        .replace("\u00AD", "")        # soft hyphen → remove entirely
        .replace("\u2026", "...")     # ellipsis → three dots
        .replace("\u201c", '"').replace("\u201d", '"')  # curly quotes → straight "
        .replace("\u201e", '"').replace("\u201f", '"')  # low‐high double quotes → straight "
        .replace("\u2018", "'").replace("\u2019", "'")  # curly apostrophes → straight '
        .replace("\u02BC", "'")       # modifier apostrophe → straight '
        .replace("\u00B4", "'")       # acute accent used as apostrophe → straight '
        .replace("\u02C8", "'")       # primary stress marker → straight apostrophe
        .replace("\u00A0", " ")       # non‐breaking space → ordinary space
        .replace("\u2002", " ").replace("\u2003", " ")   # en space, em space → space
        .replace("\u2009", " ").replace("\u202F", " ")   # thin space, narrow NBSP → space
        .replace("\u200B", "")        # zero‐width space → remove entirely
        .replace("\uFEFF", "")        # zero‐width no‐break space (BOM) → remove
        .replace("\r\n", "\n").replace("\r", "\n")  # normalize CRLF & CR → LF
    )


def _build_header(title: str, date: str, version_nb: int) -> ET.Element:
    tei = ET.Element(f"{{{TEI_NS}}}TEI", {"xml:id": f"v{version_nb}"})
    fd  = ET.SubElement(ET.SubElement(tei, f"{{{TEI_NS}}}teiHeader"),
                        f"{{{TEI_NS}}}fileDesc")

    ts  = ET.SubElement(fd, f"{{{TEI_NS}}}titleStmt")
    ET.SubElement(ts, f"{{{TEI_NS}}}title").text = title

    pub = ET.SubElement(fd, f"{{{TEI_NS}}}publicationStmt")
    ET.SubElement(pub, f"{{{TEI_NS}}}date").text = date

    src = ET.SubElement(fd, f"{{{TEI_NS}}}sourceDesc")
    ET.SubElement(src, f"{{{TEI_NS}}}p").text = "Generated by txt2tei.py"
    return tei


def create_tei_xml(input_txt: pathlib.Path,
                   pub_date_str: str,
                   titre: str,
                   version_nb: int,
                   output_tei_path: pathlib.Path) -> pathlib.Path:

    raw_text = input_txt.read_text("utf-8")

    # 1) First normalize any problematic Unicode characters
    norm_text = _normalize_characters(raw_text)

    # 2) Then collapse runs of spaces/tabs into a single space—but leave \n alone
    norm_text = _collapse_spaces_and_tabs(norm_text)

    # Build the TEI skeleton
    tei = _build_header(titre, pub_date_str, version_nb)

    body = ET.SubElement(ET.SubElement(tei, f"{{{TEI_NS}}}text"),
                         f"{{{TEI_NS}}}body")
    ET.SubElement(body, f"{{{TEI_NS}}}p").text = norm_text

    output_tei_path.parent.mkdir(parents=True, exist_ok=True)
    ET.ElementTree(tei).write(output_tei_path,
                              encoding="utf-8",
                              xml_declaration=True)
    log.info("TEI written → %s", output_tei_path)
    return output_tei_path


# ───────────────────────────────────────────────────

@click.command()
@click.argument("input_txt", type=click.Path(exists=True, dir_okay=False,
                                             path_type=pathlib.Path))
@click.option("--pub_date_str", required=True,
              help="Publication date, e.g. '1842'.")
@click.option("--titre", required=True,
              help="Title of the work.")
@click.option("--version_nb", required=True, type=int,
              help="Version number (used in xml:id).")
@click.option("--output_tei", type=click.Path(dir_okay=False,
              path_type=pathlib.Path),
              help="Output TEI file (default: same basename with .xml).")
def run(input_txt: pathlib.Path,
        pub_date_str: str,
        titre: str,
        version_nb: int,
        output_tei: pathlib.Path | None):
    logging.basicConfig(level=logging.INFO)

    if output_tei is None:
        output_tei = input_txt.with_suffix(".xml")

    create_tei_xml(input_txt, pub_date_str, titre,
                   version_nb, output_tei)
    log.info("Finished.")


if __name__ == "__main__":
    run()
